### ISSUE TITLE
NPC only killmail crashes the app

### ISSUE THREAD

**Issue by lorique** [LoriqueNET/KillFeed#13]
When loading a killmail which is made by a npc's only, the app crashes due to to nullpointer exception when trying to iterate over an array

`java.lang.RuntimeException: Could not dispatch event: class net.lorique.killfeed.storage.event.StorageKillmailEvent to handler [EventHandler public void net.lorique.killfeed.fragments.user.KillmailFragment.onKillmailLoaded(net.lorique.killfeed.storage.event.StorageKillmailEvent)]: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
	at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
	at com.squareup.otto.Bus.dispatch(Bus.java:387)
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
	at com.squareup.otto.Bus.post(Bus.java:337)
	at net.lorique.killfeed.queue.storage.StorageQueueService.onSuccess(StorageQueueService.java:53)`

**Comment by lorique** [comment]
Fixed
